name: Android CI

on:
  push:
    branches: [ "lineage-21.0" ]
  pull_request:
    branches: [ "lineage-21.0" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - run: gradle init
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
    - uses: actions/download-artifact@v4
    - name: Display structure of downloaded files
      run: ls
