name: Android CI

on:
  push:
    branches: [ "lineage-21.0" ]
  pull_request:
    branches: [ "lineage-21.0" ]

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - run: gradle init
      - run: bash ./gradlew assembleRelease
      - name: Upload release APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-unsigned.apk
          path: ${{ github.workspace }}/app-release-unsigned.apk
